# After changing this file, check it on:
#   http://lint.travis-ci.org/

os:         linux
language:   python
env:        PYTHON_EXE=python

matrix:
  fast_finish: true
  allow_failures:
    - os: windows       # tar confused by colon in C:\... names - see https://steve-parker.org/linux/tar-colon-filename/
    - os: freebsd       # missing bash
    - arch: ppc64le     # missing torchvision 0.10.1
    - arch: s390x       # missing torchvision 0.10.1

  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

    - name: "Python 3 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7, but may change with time
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: PYTHON_EXE=python3

    - name: "Python 3.6 on FreeBSD"
      os: freebsd
      language: python
      python: 3.6
      env: PYTHON_EXE=python
      before_install:
        - pkg install bash

    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - ln -s `which python.exe` python3
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - PYTHON_EXE=python.exe

    - name: "Python 3.8 on IBM Power"
      arch: ppc64le
      os: linux
      language: python
      python: 3.8
      env: PYTHON_EXE=python

    - name: "Python 3.8 on IBM Z"
      arch: s390x
      os: linux
      language: python
      python: 3.8
      env: PYTHON_EXE=python
      before_install:
        # work around cache dir owned by root (see https://travis-ci.community/t/7822/6)
        - sudo chown -fR $USER:$GROUP ~/.cache/pip/wheels

install:
    - CWD=`pwd`
    - PATH=$PATH:$CWD
    - THIS_REPO_NAME=`basename $CWD`
    - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}, TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}"
    - echo "CWD=${CWD}, THIS_REPO_NAME=${THIS_REPO_NAME}, PATH=${PATH}"
    - which ${PYTHON_EXE}
    - ${PYTHON_EXE} --version
    - wget https://raw.github.com/lehmannro/assert.sh/master/assert.sh

script:
    - ${PYTHON_EXE} function_access.py
    - ${PYTHON_EXE} param_source.py
    - ${PYTHON_EXE} runnable.py
    - ${PYTHON_EXE} stored_entry.py
    - ${PYTHON_EXE} kernel.py
    - bash test_axs.sh
