build: false

environment:
  ASSERT_URL: https://raw.github.com/lehmannro/assert.sh/master/assert.sh
  matrix:
    - job_name: Windows Py 3.6
      appveyor_build_worker_image: Visual Studio 2015
      PYTHON: C:\Python36-x64

    - job_name: Windows Py 3.9
      appveyor_build_worker_image: Visual Studio 2019
      PYTHON: C:\Python39-x64

    - job_name: MacOS
      appveyor_build_worker_image: macos

    - job_name: Linux
      appveyor_build_worker_image: Ubuntu

init:
    - cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%cd%;%PATH%
    - sh: export PATH=$APPVEYOR_BUILD_FOLDER:$PATH

install:
    - cmd: mklink python3.exe %PYTHON%\\python.exe
    - python3 --version
    - cmd: appveyor DownloadFile %ASSERT_URL%
    - sh: appveyor DownloadFile $ASSERT_URL

test_script:
    - function_access.py
    - param_source.py
    - runnable.py
    - stored_entry.py
    - kernel.py
    - axs version
    - cmd: bash test_axs.sh
    - sh: test_axs.sh
