build: false

environment:
  ASSERT_URL: https://raw.github.com/lehmannro/assert.sh/master/assert.sh
  matrix:
    - job_name: Windows classification Py=3.10
      appveyor_build_worker_image: Visual Studio 2019
      PYTHON_DIR: C:\Python310-x64
      ONNX_CLASSIFY: on
      PYTORCH_CLASSIFY: on
      TF_CLASSIFY: on

    - job_name: Windows detection+Bert Py=3.10
      appveyor_build_worker_image: Visual Studio 2019
      PYTHON_DIR: C:\Python310-x64
      ONNX_DETECTION: on
      ONNX_BERT_SQUAD: on
      PYTORCH_BERT_DEMO: on

    - job_name: MacOS Bert
      appveyor_build_worker_image: macos-catalina
      ONNX_BERT_SQUAD: on
      PYTORCH_BERT_DEMO: on

    - job_name: MacOS detection
      appveyor_build_worker_image: macos-catalina
      ONNX_DETECTION: on

    - job_name: MacOS compile+classification
      appveyor_build_worker_image: macos-catalina
      PACKAGE_INSTALL_AND_IMPORT: on
      C_COMPILE_AND_RUN: on
      ONNX_CLASSIFY: on

    - job_name: Linux detection+Bert
      appveyor_build_worker_image: Ubuntu
      ONNX_DETECTION: on
      ONNX_BERT_SQUAD: on
      PYTORCH_BERT_DEMO: on

    - job_name: Linux compile+classification
      appveyor_build_worker_image: Ubuntu
      PACKAGE_INSTALL_AND_IMPORT: on
      C_COMPILE_AND_RUN: on
      ONNX_CLASSIFY: on
      PYTORCH_CLASSIFY: on
      TF_CLASSIFY: on

    - job_name: Windows Bert Py=3.6
      appveyor_build_worker_image: Visual Studio 2019
      PYTHON_DIR: C:\Python36-x64
      ONNX_BERT_SQUAD: on
      PYTORCH_BERT_DEMO: on

    - job_name: Windows detection Py=3.6
      appveyor_build_worker_image: Visual Studio 2019
      PYTHON_DIR: C:\Python36-x64
      ONNX_DETECTION: on

    - job_name: Windows classification Py=3.6
      appveyor_build_worker_image: Visual Studio 2019
      PYTHON_DIR: C:\Python36-x64
      PACKAGE_INSTALL_AND_IMPORT: on
      ONNX_CLASSIFY: on
      PYTORCH_CLASSIFY: on

init:
    - cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f
    - cmd: set PYTHON_EXE=python3
    - cmd: set PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%cd%;%PATH%
    - sh: export PATH=$APPVEYOR_BUILD_FOLDER:$PATH

install:
    - cmd: mklink %PYTHON_DIR%\\python3.exe %PYTHON_DIR%\\python.exe
    - axs func platform.platform
    - python3 --version
    - sh: |
        if [[ "$CI_LINUX" == "true" ]]; then
            appveyor DownloadFile "https://bootstrap.pypa.io/pip/3.6/get-pip.py"
            sudo python3 get-pip.py "pip==19.3.1"
        fi
    - python3 -m pip --version
    - cmd: appveyor DownloadFile %ASSERT_URL%
    - sh: appveyor DownloadFile $ASSERT_URL

test_script:
    - function_access.py
    - param_source.py
    - runnable.py
    - stored_entry.py
    - kernel.py
    - axs version
    - cmd: bash test_axs.sh
    - sh: test_axs.sh
