name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - job_name: Windows classification Py=3.10
            os: windows-latest
            python-version: 3.10
            env:
              ONNX_CLASSIFY: 'on'
              PYTORCH_CLASSIFY: 'on'
              TF_CLASSIFY: 'on'

          - job_name: Windows detection+Bert Py=3.10
            os: windows-latest
            python-version: 3.10
            env:
              ONNX_DETECTION: 'on'
              ONNX_BERT_SQUAD: 'on'
              PYTORCH_BERT_DEMO: 'on'

          - job_name: MacOS Bert
            os: macOS-catalina
            python-version: 3.9
            env:
              ONNX_BERT_SQUAD: 'on'
              PYTORCH_BERT_DEMO: 'on'

          - job_name: MacOS detection
            os: macOS-catalina
            python-version: 3.9
            env:
              ONNX_DETECTION: 'on'

          - job_name: MacOS compile+classification
            os: macOS-catalina
            python-version: 3.9
            env:
              PACKAGE_INSTALL_AND_IMPORT: 'on'
              C_COMPILE_AND_RUN: 'on'
              ONNX_CLASSIFY: 'on'

          - job_name: Linux detection+Bert
            os: ubuntu-latest
            python-version: 3.9
            env:
              ONNX_DETECTION: 'on'
              ONNX_BERT_SQUAD: 'on'
              PYTORCH_BERT_DEMO: 'on'

          - job_name: Linux compile+classification
            os: ubuntu-latest
            python-version: 3.9
            env:
              PACKAGE_INSTALL_AND_IMPORT: 'on'
              C_COMPILE_AND_RUN: 'on'
              ONNX_CLASSIFY: 'on'
              PYTORCH_CLASSIFY: 'on'
              TF_CLASSIFY: 'on'

          - job_name: Windows Bert Py=3.6
            os: windows-latest
            python-version: 3.6
            env:
              ONNX_BERT_SQUAD: 'on'
              PYTORCH_BERT_DEMO: 'on'

          - job_name: Windows detection Py=3.6
            os: windows-latest
            python-version: 3.6
            env:
              ONNX_DETECTION: 'on'

          - job_name: Windows classification Py=3.6
            os: windows-latest
            python-version: 3.6
            env:
              PACKAGE_INSTALL_AND_IMPORT: 'on'
              ONNX_CLASSIFY: 'on'
              PYTORCH_CLASSIFY: 'on'

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.job_name }}

    env:
      ASSERT_URL: https://raw.github.com/lehmannro/assert.sh/master/assert.sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Initialize environment
        if: matrix.os == 'windows-latest'
        run: |
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /
